# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlpkg < Formula
  desc "SQLite package manager"
  homepage "https://github.com/nalgeon/sqlpkg-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nalgeon/sqlpkg-cli/releases/download/v0.3.0/sqlpkg-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "3a28b1a0f1ad772a5fff0e915202a9bce0ae8d570add958764f2438430bc963d"

      def install
        bin.install "sqlpkg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nalgeon/sqlpkg-cli/releases/download/v0.3.0/sqlpkg-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "3ea6df8e9b52e79bee73f4890b2b516a9a0a4ad9689839c07940cc0eecffed90"

      def install
        bin.install "sqlpkg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nalgeon/sqlpkg-cli/releases/download/v0.3.0/sqlpkg-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "b0976af8a54b14e65d312b6aa893121010586b4f06e929946ff47cef685182c5"
      def install
        bin.install "sqlpkg"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nalgeon/sqlpkg-cli/releases/download/v0.3.0/sqlpkg-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "e755b043d4eb4af218bc2b3a52809e6d11599522740b5ab6bf3b523ce4d7fda0"
      def install
        bin.install "sqlpkg"
      end
    end
  end
end
