name: build

on:
    push:
        branches: [main]
        paths:
            - .github/**
            - cmd/**
            - internal/**
            - main.go
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "go.mod"

            - name: Install dependencies
              run: go get .

            - name: Build
              run: go build -v .

            - name: Test
              run: go test -v ./...
